spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_tecobrary?serverTimezone=UTC
    username: luffy
    password: 159456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
